version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/app/
    command: sh -c './wait-for.sh postgres:5432 -- make run'
  postgres:
    image: postgres:12.1
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  openapi:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./gen/http/openapi3.yaml:/openapi.yaml
    env_file:
      - ./.env
    environment:
      SWAGGER_JSON: /openapi.yaml
volumes:
  postgres_data:
